namespace Inspire.Annotator.Annotations
{
    public class FieldModel : EntityModel
    {
        public FieldModel(int row,int order, int? width, string id, bool isKey, string displayName, bool autogenerated, ControlType controlType, string tabId, string entityId, bool isRequired) : base(order, width, id, isKey, displayName, entityId)
        {
            Row = row;
            Autogenerated = autogenerated;
            ControlType = controlType.ToString().ToLower();
            TabId = tabId;
            IsRequired = isRequired;
            Hidden = controlType == Annotations.ControlType.Hidden;
        }
        public bool Hidden { get; }
        public int Row { get; set; }
        public int? MinimumLength { get; set; }
        public int MaximumLength { get; set; }
        public bool Autogenerated { get; }
        public string TabId { get; }
        public string DefaultValue { get; set; }
        public string ControlType { get; }
        public bool IsRequired { get; }
        public ListModel List { get; set; }
    }
}
