namespace Inspire.Security.Models
{
    public class ReportTab
    {
        public ReportTab()
        {
            ReportRows = new List<ReportRow>();
        }
        public string ID { get; set; }
        public string Name { get; set; }
        public int Order { get; set; }
        public bool IsActive { get; set; }
        public string ReportID { get; set; }
        public Report Report { get; set; }
        public List<ReportRow> ReportRows { get; set; }
    }
    public class ReportField
    {
        public string ReportRowID { get; set; }
        public ReportRow ReportRow { get; set; }
        public int Order { get; set; }
        public int Grids { get; set; }
        public string Label { get; set; }
        public string Type { get; set; }
        public string DataType { get; set; }
        public bool Autogenerated { get; set; }
        public bool Hidden { get; set; }
        public string ID { get; set; }
        public bool IsDate { get; set; }
        public bool IsDropDown { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string TextField { get; set; }
        public string SortField { get; set; }
        public string ValueField { get; set; }
        public string Area { get; set; }
        public bool MultpleSelect { get; set; }
        public string OnSelectedChange { get; set; }
        public string OnField { get; set; }
        public string DefaultValue { get; set; }
        public string AllowedValue { get; set; }
        public string FilterColumn { get; set; }
        public string FilterValue { get; set; }
        public string TabID { get; set; }
        public int? MinimumLength { get; set; }
        public int? MaximumLength { get; set; }
        public bool IsRequired { get; set; }

    }

}
